astro_dash/config/routes.rb
AstroDash::Application.routes.draw do
  
  
  root 'welcome#index'
  
  get "welcome/index"
  
  get 'content/:name' => 'content_pages#show'
  
  namespace :admin do
    post 'orders/send' => 'orders#send_documents'
    
    resources :services, :content_pages, :events, :orders
    get "index" => 'orders#index'
    
  end
  
  resources :services, :content_pages, :events, :only => [:index, :show]
  
  resources :orders, :only => [:show, :new, :create]
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  

end

astro_dash/app/models/content_page.rb
class ContentPage < ActiveRecord::Base
  
  include HTML_Sanitize
    
  before_save do
    self.body = sanitize(self.body)
  end
  
end

astro_dash/app/models/event.rb
class Event < ActiveRecord::Base
  
  include HTML_Sanitize
    
  before_save do
    self.description = sanitize(self.description)
  end
end

astro_dash/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :service
  
end

astro_dash/app/models/service.rb
class Service < ActiveRecord::Base
  
  include HTML_Sanitize
  
  before_save do
    self.description = sanitize(self.description)
    self.required_info = sanitize(self.required_info)
  end
  
  validates :name, presence: true, length: {minimum: 5}
  validates :price, presence: true, numericality: true
end

astro_dash/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  
  # authenticate all requests to controllers in admin namespace
  before_filter :authenticate
  
  protected
  
  def authenticate
    if session[:username] != APP_CONFIG['username']
      redirect_to root_path
    end
  end
    
end

astro_dash/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

astro_dash/app/controllers/content_pages_controller.rb
class ContentPagesController < ApplicationController
  
  def show
    @content_pages = ContentPage.where(:category => params[:name]).all
  end
  
  def index
    @content_pages = ContentPage.find(:all, category: params[:name])
  end
  
end

astro_dash/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @events = Event.all
  end

end

astro_dash/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
    if @service.nil?
      @service = Service.find(params[:service_id])
    end
    @order = Order.new(:service => @service)
  end
  
  def show
    @order = Order.find(params[:id])
  end
  
  def create
    @order = Order.new(order_params)
    if @order.save
      OrderMailer.confirmation_email(@order).deliver
      redirect_to @order
    else
      render new
    end
  end
  
  private
    def order_params
      params.require(:order).permit(:customer, :customer_info, :email, :service_id)
    end
  
end

astro_dash/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  
  def index
    @services = Service.all
  end
  
  def show
    @service = Service.find(params[:id])
  end
  
  
end

astro_dash/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    login_id = params[:session][:login]
    login_pass = params[:session][:password]
    
    # if valid login, set session username
    if login_id == APP_CONFIG['username'] and login_pass == APP_CONFIG['password']
      session[:username] = login_id
      redirect_to admin_index_path
    else
      flash[:danger] = 'invalid login'
      render 'new'
    end
  end

  def destroy
    # username is only session variable, so simply reset entire session
    reset_session
    redirect_to root_path
  end
end

astro_dash/app/controllers/welcome_controller.rb
require 'rss'
require 'open-uri'

class WelcomeController < ApplicationController
  
  def index
    blog_rss_url = APP_CONFIG['rss_url']
    get_rss(blog_rss_url)
  end
  
  private
    def get_rss(rss_url)
      open(rss_url) do |rss|
        @feed = RSS::Parser.parse(rss)
      end
    end
end

astro_dash/app/helpers/admin_helper.rb
module AdminHelper
end

astro_dash/app/helpers/application_helper.rb
module ApplicationHelper
end

astro_dash/app/helpers/content_page_helper.rb
module ContentPageHelper
end

astro_dash/app/helpers/event_helper.rb
module EventHelper
end

astro_dash/app/helpers/orders_helper.rb
module OrdersHelper
  
  # checks if order is filled, if so, formats date
  def check_order_filled(order)
    order.filled_on.nil? ? "Not filled" : order.filled_on.to_formatted_s(:long)
  end
end

astro_dash/app/helpers/services_helper.rb
module ServicesHelper
end

astro_dash/app/helpers/sessions_helper.rb
module SessionsHelper
end

astro_dash/app/helpers/welcome_helper.rb
module WelcomeHelper
end

astro_dash/app/views/admin/index.html.erb
<h1>Admin</h1>
<h2>Orders</h2>
<table>
  <tr>
    <th>Order #</th>
    <th>Name</th>
    <th>Service</th>
    <th colspan="3"></th>
  </tr>
 
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.customer %></td>
      <td><%= order.service %></td>
      <td><%= link_to 'View order', admin_order_path(order) %></td>
      <td><%= link_to 'Edit', edit_admin_order_path(order) %></td>
      <td><%= link_to 'Destroy', admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Edit Content', admin_content_pages_path %>
<%= link_to 'Edit Events', admin_events_path %>

astro_dash/app/views/admin/login.html.erb
<h1>Please Login:</h1>

astro_dash/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AstroDash</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-banner" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <h1>Admin Control <small><%= link_to("logout", logout_path, :method => :delete) %></small></h1>
        </div>
    </div>
</nav>
<%= render partial: "shared/nav_banner" %>
<%= yield %>

</body>
</html>

astro_dash/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AstroDash</title>
  <link href='//fonts.googleapis.com/css?family=Merriweather:300italic,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "shared/nav_banner" %>
<%= yield %>
  <div class="footer">
    <p>Application development by <a href="//beaudavenport.github.io">Beau Davenport</a>
    | <%= link_to 'Admin Login', login_path %></p>
  </div>
</body>
</html>

astro_dash/app/views/shared/_full_editor.html.erb
<!-- editor toolbar -->
<div class="btn-toolbar" data-role="editor-toolbar" data-target="#editor">
    <div class="btn-group">
        <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="fa fa-text-height"></i>&nbsp;<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a data-edit="fontSize 7"><font size="7">Giant</font></a></li>
            <li><a data-edit="fontSize 5"><font size="5">Huge</font></a></li>
            <li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
            <li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
        </ul>
    </div>
    <div class="btn-group">
        <a class="btn btn-default" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="fa fa-bold"></i></a>
        <a class="btn btn-default" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="fa fa-italic"></i></a>
        <a class="btn btn-default" data-edit="strikethrough" title="Strikethrough"><i class="fa fa-strikethrough"></i></a>
        <a class="btn btn-default" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="fa fa-underline"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default" data-edit="insertunorderedlist" title="Bullet list"><i class="fa fa-list-ul"></i></a>
        <a class="btn btn-default" data-edit="insertorderedlist" title="Number list"><i class="fa fa-list-ol"></i></a>
        <a class="btn btn-default" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="fa fa-outdent"></i></a>
        <a class="btn btn-default" data-edit="indent" title="Indent (Tab)"><i class="fa fa-indent"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="fa fa-align-left"></i></a>
        <a class="btn btn-default" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="fa fa-align-center"></i></a>
        <a class="btn btn-default" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="fa fa-align-right"></i></a>
        <a class="btn btn-default" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="fa fa-align-justify"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="fa fa-link"></i></a>
        <div class="dropdown-menu input-append">
            <input class="span2" placeholder="URL" type="text" data-edit="createLink"/>
            <button class="btn btn-default" type="button">Add</button>
        </div>
    </div>
    <div class="btn-group">
        <a class="btn btn-default" data-edit="unlink" title="Remove Hyperlink"><i class="fa fa-cut"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default" title="Insert picture (or just drag & drop)" id="pictureBtn"><i class="fa fa-picture-o"></i></a>
        <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" style="opacity: 0; position: absolute; top: 0px; left: 0px; width: 42px; height: 32px;" />
    </div>
    <div class="btn-group">    
        <a class="btn btn-default" id="iconMode" title="Icon mode" data-edit="fontName AstroGadget"><i class="fa fa-moon-o"></i></a>
        <a class="btn btn-default" title="Toggle icon guide" data-toggle="collapse" data-target="#iconGuide"><i class="fa fa-info-circle"></i></a>
        <a class="btn btn-default" title="Text mode" data-edit="fontName sans-serif"><i class="fa fa-font"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="fa fa-undo"></i></a>
        <a class="btn btn-default" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="fa fa-repeat"></i></a>
    </div>
</div>
<br />
<div class="panel panel-default">
    
    <!-- collapsed icon guide -->
    <div class="collapse well well-sm" id="iconGuide">
        <p>
            <span class="gadget">A</span> - A &nbsp; <span class="gadget">B</span> - B &nbsp; <span class="gadget">C</span> - C &nbsp;
            <span class="gadget">D</span> - D &nbsp; <span class="gadget">E</span> - E &nbsp; <span class="gadget">F</span> - F &nbsp;
            <span class="gadget">G</span> - G &nbsp; <span class="gadget">H</span> - H &nbsp; <span class="gadget">I</span> - I &nbsp;
            <span class="gadget">J</span> - J &nbsp; <span class="gadget">K</span> - K &nbsp; <span class="gadget">L</span> - L &nbsp;
            <span class="gadget">M</span> - M &nbsp; <span class="gadget">N</span> - M &nbsp; <span class="gadget">O</span> - O &nbsp;
            <span class="gadget">P</span> - P &nbsp; <span class="gadget">Q</span> - Q &nbsp; <span class="gadget">R</span> - R &nbsp;
            <span class="gadget">a</span> - a &nbsp; <span class="gadget">b</span> - b &nbsp; <span class="gadget">c</span> - c &nbsp;
            <span class="gadget">d</span> - d &nbsp; <span class="gadget">e</span> - e &nbsp; <span class="gadget">f</span> - f &nbsp;
            <span class="gadget">g</span> - g &nbsp; <span class="gadget">h</span> - h &nbsp; <span class="gadget">i</span> - i &nbsp;
            <span class="gadget">j</span> - j &nbsp; <span class="gadget">k</span> - k &nbsp; <span class="gadget">l</span> - l &nbsp;
            <span class="gadget">$</span> - $ &nbsp; <span class="gadget">*</span> - * &nbsp; <span class="gadget">%</span> - % &nbsp;
            <span class="gadget">"</span> - " &nbsp; <span class="gadget">'</span> - ' &nbsp; <span class="gadget">#</span> - # &nbsp;
            <span class="gadget">&</span> - & &nbsp; <span class="gadget">(</span> - ( &nbsp; <span class="gadget">)</span> - ) &nbsp;
            <span class="gadget">!</span> - ! &nbsp;
        </p>    
    </div>
    
    <!-- editor div -->
    <div id="editor" contenteditable="true">
        <%= content.html_safe %>
    </div>
    
</div>

astro_dash/app/views/shared/_lite_editor.html.erb
<div class="btn-toolbar" data-role="editor-toolbar" data-target="#editor">
    <div class="btn-group">
        <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="fa fa-text-height"></i>&nbsp;<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a data-edit="fontSize 7"><font size="7">Giant</font></a></li>
            <li><a data-edit="fontSize 5"><font size="5">Huge</font></a></li>
            <li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
            <li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
        </ul>
    </div>
    <div class="btn-group">
        <a class="btn btn-default" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="fa fa-bold"></i></a>
        <a class="btn btn-default" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="fa fa-italic"></i></a>
        <a class="btn btn-default" data-edit="strikethrough" title="Strikethrough"><i class="fa fa-strikethrough"></i></a>
        <a class="btn btn-default" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="fa fa-underline"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default" data-edit="insertunorderedlist" title="Bullet list"><i class="fa fa-list-ul"></i></a>
        <a class="btn btn-default" data-edit="insertorderedlist" title="Number list"><i class="fa fa-list-ol"></i></a>
        <a class="btn btn-default" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="fa fa-outdent"></i></a>
        <a class="btn btn-default" data-edit="indent" title="Indent (Tab)"><i class="fa fa-indent"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="fa fa-align-left"></i></a>
        <a class="btn btn-default" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="fa fa-align-center"></i></a>
        <a class="btn btn-default" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="fa fa-align-right"></i></a>
        <a class="btn btn-default" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="fa fa-align-justify"></i></a>
    </div>
    <div class="btn-group">
        <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="fa fa-link"></i></a>
        <div class="dropdown-menu input-append">
            <input class="span2" placeholder="URL" type="text" data-edit="createLink"/>
            <button class="btn btn-default" type="button">Add</button>
        </div>
    </div>
    <div class="btn-group">
        <a class="btn btn-default" data-edit="unlink" title="Remove Hyperlink"><i class="fa fa-cut"></i></a>
    </div>

    <div class="btn-group">
        <a class="btn btn-default" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="fa fa-undo"></i></a>
        <a class="btn btn-default" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="fa fa-repeat"></i></a>
    </div>
</div>
<br />
<div class="panel panel-default">
    
    <!-- editor div -->
    <div id="editor" contenteditable="true">
        Edit text here!
    </div>
    
</div>

astro_dash/app/views/shared/_nav_banner.html.erb
<!-- Banner with heading and navbar -->

<div class="banner row">
    <div class="banner-inner col-xs-12 col-sm-12 col-md-12">
        <div class="spacer">
        </div>
        <div class="banner-title">
            <h1>Nikki Davenport</h1>
            <p class="text-light">Astrological Services</p>
        </div>
        <nav class="navbar navbar-default navbar-banner" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <p class="navbar-text visible-xs">Click here to explore...</p>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                      <li><a href="/">Home</a></li>
                      <li><a href="/services.html">Services</a></li>
                      <li><a href="/content/signs">Signs of the Zodiac</a></li>
                      <li><a href="/content/planets">Planets</a></li>
                      <li><a href="/content/houses">Houses</a></li>
                      <li><a href="/events">Events</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>