astro_dash/config/routes.rb
AstroDash::Application.routes.draw do
  
  
  root 'welcome#index'
  
  get "welcome/index"
  
  get 'content/:name' => 'content_pages#show'
  
  namespace :admin do
    post 'orders/send' => 'orders#send_documents'
    
    resources :services, :content_pages, :events, :orders
    get "index" => 'orders#index'
    
  end
  
  resources :services, :content_pages, :events, :only => [:index, :show]
  
  resources :orders, :only => [:show, :new, :create]
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  

end

astro_dash/app/models/concerns/html_sanitize.rb
# HTML Sanitizer
module HTML_Sanitize 
  extend ActiveSupport::Concern
  
  require 'sanitize'
  
  # sanitize HTML input using white list array of allowable HTML tags in config variables
  def sanitize(input) 
    Sanitize.fragment(input, 
      :elements => APP_CONFIG['HTML_white_list']['elements'],
      :attributes => {
        :all => APP_CONFIG['HTML_white_list']['attributes']
      })
  end
  
end

astro_dash/app/models/content_page.rb
class ContentPage < ActiveRecord::Base
  
  include HTML_Sanitize
    
  before_save do
    self.body = sanitize(self.body)
  end
  
end

astro_dash/app/models/event.rb
class Event < ActiveRecord::Base
  
  include HTML_Sanitize
    
  before_save do
    self.description = sanitize(self.description)
  end
end

astro_dash/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :service
  
end

astro_dash/app/models/service.rb
class Service < ActiveRecord::Base
  
  include HTML_Sanitize
  
  before_save do
    self.description = sanitize(self.description)
    self.required_info = sanitize(self.required_info)
  end
  
  validates :name, presence: true, length: {minimum: 5}
  validates :price, presence: true, numericality: true
end

astro_dash/app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminController
  
  def index
    @services = Service.all
  end
  
  def new
    @service = Service.new
  end
  
  def create
    @service = Service.new(service_params)
    
    if @service.save
      redirect_to [:admin, @service]
    else
      render 'new'
    end
    
  end
  
  def show
    @service = Service.find(params[:id])
  end
  
  def edit
    @service = Service.find(params[:id])
  end
  
  def update
    @service = Service.find(params[:id])
   
    if @service.update(service_params)
      redirect_to [:admin, @service]
    else
      render 'edit'
    end
  end
  
  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    
    redirect_to admin_services_path
  end
  
  private
    def service_params
      params.require(:service).permit(:name, :description, :price, :required_info)
    end
  
end

astro_dash/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  
  # authenticate all requests to controllers in admin namespace
  before_filter :authenticate
  
  protected
  
  def authenticate
    if session[:username] != APP_CONFIG['username']
      redirect_to root_path
    end
  end
    
end

astro_dash/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

astro_dash/app/controllers/content_pages_controller.rb
class ContentPagesController < ApplicationController
  
  def show
    @content_pages = ContentPage.where(:category => params[:name]).all
  end
  
  def index
    @content_pages = ContentPage.find(:all, category: params[:name])
  end
  
end

astro_dash/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @events = Event.all
  end

end

astro_dash/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
    if @service.nil?
      @service = Service.find(params[:service_id])
    end
    @order = Order.new(:service => @service)
  end
  
  def show
    @order = Order.find(params[:id])
  end
  
  def create
    @order = Order.new(order_params)
    if @order.save
      OrderMailer.confirmation_email(@order).deliver
      redirect_to @order
    else
      render new
    end
  end
  
  private
    def order_params
      params.require(:order).permit(:customer, :customer_info, :email, :service_id)
    end
  
end

astro_dash/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  
  def index
    @services = Service.all
  end
  
  def show
    @service = Service.find(params[:id])
  end
  
  
end

astro_dash/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    login_id = params[:session][:login]
    login_pass = params[:session][:password]
    
    # if valid login, set session username
    if login_id == APP_CONFIG['username'] and login_pass == APP_CONFIG['password']
      session[:username] = login_id
      redirect_to admin_index_path
    else
      flash[:danger] = 'invalid login'
      render 'new'
    end
  end

  def destroy
    # username is only session variable, so simply reset entire session
    reset_session
    redirect_to root_path
  end
end

astro_dash/app/controllers/welcome_controller.rb
require 'rss'
require 'open-uri'

class WelcomeController < ApplicationController
  
  def index
    blog_rss_url = APP_CONFIG['rss_url']
    get_rss(blog_rss_url)
  end
  
  private
    def get_rss(rss_url)
      open(rss_url) do |rss|
        @feed = RSS::Parser.parse(rss)
      end
    end
end

astro_dash/app/helpers/admin/event_helper.rb
module Admin::EventHelper
end

astro_dash/app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

astro_dash/app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

astro_dash/app/helpers/admin_helper.rb
module AdminHelper
end

astro_dash/app/helpers/application_helper.rb
module ApplicationHelper
end

astro_dash/app/helpers/content_page_helper.rb
module ContentPageHelper
end

astro_dash/app/helpers/event_helper.rb
module EventHelper
end

astro_dash/app/helpers/orders_helper.rb
module OrdersHelper
  
  # checks if order is filled, if so, formats date
  def check_order_filled(order)
    order.filled_on.nil? ? "Not filled" : order.filled_on.to_formatted_s(:long)
  end
end

astro_dash/app/helpers/services_helper.rb
module ServicesHelper
end

astro_dash/app/helpers/sessions_helper.rb
module SessionsHelper
end

astro_dash/app/helpers/welcome_helper.rb
module WelcomeHelper
end

astro_dash/app/views/admin/services/_form.html.erb
<%= form_for [:admin, @service] do |s| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited
        this service from being saved:</h2>
      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
      <%= s.label :name %><br />
      <%= s.text_field :name %>
  </p>
  <%= s.hidden_field :description %>
  
  <!-- if no content, set to default 'Enter text here', otherwise render content for editing -->
  <% if @service.description.nil? %>
    <%= render partial: 'shared/full_editor', locals: {content: "Enter text here"} %>
  <% else %>
    <%= render partial: 'shared/full_editor', locals: {content: @service.description} %>
  <% end %>
  
  <p>
      <%= s.label :required_info %><br />
      <%= s.text_field :required_info %>
  </p>
  
  <p>
    <%= s.label :price %><br />
    <%= s.text_field :price %>
  </p>
  <p>
    <%= s.submit %>
  </p>
<% end %>

astro_dash/app/views/admin/services/edit.html.erb
<h1>Edit a Service</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_services_path %>

astro_dash/app/views/admin/services/index.html.erb
<h1>Listing services</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th colspan="3"></th>
  </tr>
 
  <% @services.each do |service| %>
    <tr>
      <td><%= service.name %></td>
      <td><%= service.description %></td>
      <td><%= service.price %></td>
      <td><%= link_to 'Show', admin_service_path(service) %></td>
      <td><%= link_to 'Edit', edit_admin_service_path(service) %></td>
      <td><%= link_to 'Destroy', admin_service_path(service), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Service', new_admin_service_path %>

astro_dash/app/views/admin/services/new.html.erb
<h1>Add a Service</h1>


<div class="btn-toolbar" data-role="editor-toolbar" data-target="#editor">
<div class="btn-group">
<a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="icon-font"></i><b class="caret"></b></a>
<ul class="dropdown-menu">
</ul>
</div>
<div class="btn-group">
<a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="icon-text-height"></i>&nbsp;<b class="caret"></b></a>
<ul class="dropdown-menu">
<li><a data-edit="fontSize 5"><font size="5">Huge</font></a></li>
<li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
<li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
</ul>
</div>
<div class="btn-group">
<a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="icon-bold"></i></a>
<a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="icon-italic"></i></a>
<a class="btn" data-edit="strikethrough" title="Strikethrough"><i class="icon-strikethrough"></i></a>
<a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="icon-underline"></i></a>
</div>
<div class="btn-group">
<a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i class="icon-list-ul"></i></a>
<a class="btn" data-edit="insertorderedlist" title="Number list"><i class="icon-list-ol"></i></a>
<a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="icon-indent-left"></i></a>
<a class="btn" data-edit="indent" title="Indent (Tab)"><i class="icon-indent-right"></i></a>
</div>
<div class="btn-group">
<a class="btn" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="icon-align-left"></i></a>
<a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="icon-align-center"></i></a>
<a class="btn" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="icon-align-right"></i></a>
<a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="icon-align-justify"></i></a>
</div>
<div class="btn-group">
<a class="btn dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="icon-link"></i></a>
<div class="dropdown-menu input-append">
<input class="span2" placeholder="URL" type="text" data-edit="createLink"/>
<button class="btn" type="button">Add</button>
</div>
<a class="btn" data-edit="unlink" title="Remove Hyperlink"><i class="icon-cut"></i></a>
</div>
<div class="btn-group">
<a class="btn" title="Insert picture (or just drag & drop)" id="pictureBtn"><i class="icon-picture"></i></a>
<input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" />
</div>
<div class="btn-group">
<a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="icon-undo"></i></a>
<a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="icon-repeat"></i></a>
</div>
<input type="text" data-edit="inserttext" id="voiceBtn" x-webkit-speech="">
</div>
<div id="editor">
Go ahead&hellip;
</div>
</div>
<%= link_to 'Back', admin_services_path %>

astro_dash/app/views/admin/services/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @service.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @service.description.html_safe %>
</p>

<p>
    <strong>price:</strong>
    <%= @service.price %>
</p>
<%= link_to 'Back', admin_services_path %>
| <%= link_to 'Edit', edit_admin_service_path(@service) %>