astro_dash/config/routes.rb
AstroDash::Application.routes.draw do
  
  
  root 'welcome#index'
  
  get "welcome/index"
  
  get 'content/:name' => 'content_pages#show'
  
  namespace :admin do
    post 'orders/send' => 'orders#send_documents'
    
    resources :services, :content_pages, :events, :orders
    get "index" => 'orders#index'
    
  end
  
  resources :services, :content_pages, :events, :only => [:index, :show]
  
  resources :orders, :only => [:show, :new, :create]
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  

end

astro_dash/app/models/concerns/html_sanitize.rb
# HTML Sanitizer
module HTML_Sanitize 
  extend ActiveSupport::Concern
  
  require 'sanitize'
  
  # sanitize HTML input using white list array of allowable HTML tags in config variables
  def sanitize(input) 
    Sanitize.fragment(input, 
      :elements => APP_CONFIG['HTML_white_list']['elements'],
      :attributes => {
        :all => APP_CONFIG['HTML_white_list']['attributes']
      })
  end
  
end

astro_dash/app/models/content_page.rb
class ContentPage < ActiveRecord::Base
  
  include HTML_Sanitize
    
  before_save do
    self.body = sanitize(self.body)
  end
  
end

astro_dash/app/models/event.rb
class Event < ActiveRecord::Base
  
  include HTML_Sanitize
    
  before_save do
    self.description = sanitize(self.description)
  end
end

astro_dash/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :service
  
end

astro_dash/app/models/service.rb
class Service < ActiveRecord::Base
  
  include HTML_Sanitize
  
  before_save do
    self.description = sanitize(self.description)
    self.required_info = sanitize(self.required_info)
  end
  
  validates :name, presence: true, length: {minimum: 5}
  validates :price, presence: true, numericality: true
end

astro_dash/app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  
  def index
    @orders = Order.all
  end
  
  def show
    @order = Order.find(params[:id])
  end
  
  def create
    @order = Order.new(order_params)
    
    if @order.save
      redirect_to [:admin, @order]
    else
      render 'new'
    end
    
  end
  
  def edit
    @order = Order.find(params[:id])
  end
  
  def update
    @order = Order.find(params[:id])
   
    if @order.update(order_params)
      redirect_to [:admin, @order]
    else
      render 'edit'
    end
  end
  
  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    
    redirect_to admin_index_path
  end
  
  # Generate email with link to service documents, update order status
  def send_documents
    @docs = ActiveSupport::JSON.decode(params[:files])
    @order = Order.find(params[:id])
    DocumentMailer.document_email(@docs, @order).deliver
    
    # update filled on date with current date
    @order.filled_on = Date.today
    @order.save
    render :json => @order.filled_on
  end
  
  private
    def order_params
      params.require(:order).permit(:name, :description, :price)
    end
    
end

astro_dash/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  
  # authenticate all requests to controllers in admin namespace
  before_filter :authenticate
  
  protected
  
  def authenticate
    if session[:username] != APP_CONFIG['username']
      redirect_to root_path
    end
  end
    
end

astro_dash/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

astro_dash/app/controllers/content_pages_controller.rb
class ContentPagesController < ApplicationController
  
  def show
    @content_pages = ContentPage.where(:category => params[:name]).all
  end
  
  def index
    @content_pages = ContentPage.find(:all, category: params[:name])
  end
  
end

astro_dash/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @events = Event.all
  end

end

astro_dash/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
    if @service.nil?
      @service = Service.find(params[:service_id])
    end
    @order = Order.new(:service => @service)
  end
  
  def show
    @order = Order.find(params[:id])
  end
  
  def create
    @order = Order.new(order_params)
    if @order.save
      OrderMailer.confirmation_email(@order).deliver
      redirect_to @order
    else
      render new
    end
  end
  
  private
    def order_params
      params.require(:order).permit(:customer, :customer_info, :email, :service_id)
    end
  
end

astro_dash/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  
  def index
    @services = Service.all
  end
  
  def show
    @service = Service.find(params[:id])
  end
  
  
end

astro_dash/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    login_id = params[:session][:login]
    login_pass = params[:session][:password]
    
    # if valid login, set session username
    if login_id == APP_CONFIG['username'] and login_pass == APP_CONFIG['password']
      session[:username] = login_id
      redirect_to admin_index_path
    else
      flash[:danger] = 'invalid login'
      render 'new'
    end
  end

  def destroy
    # username is only session variable, so simply reset entire session
    reset_session
    redirect_to root_path
  end
end

astro_dash/app/controllers/welcome_controller.rb
require 'rss'
require 'open-uri'

class WelcomeController < ApplicationController
  
  def index
    blog_rss_url = APP_CONFIG['rss_url']
    get_rss(blog_rss_url)
  end
  
  private
    def get_rss(rss_url)
      open(rss_url) do |rss|
        @feed = RSS::Parser.parse(rss)
      end
    end
end

astro_dash/app/helpers/admin/event_helper.rb
module Admin::EventHelper
end

astro_dash/app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

astro_dash/app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

astro_dash/app/helpers/admin_helper.rb
module AdminHelper
end

astro_dash/app/helpers/application_helper.rb
module ApplicationHelper
end

astro_dash/app/helpers/content_page_helper.rb
module ContentPageHelper
end

astro_dash/app/helpers/event_helper.rb
module EventHelper
end

astro_dash/app/helpers/orders_helper.rb
module OrdersHelper
  
  # checks if order is filled, if so, formats date
  def check_order_filled(order)
    order.filled_on.nil? ? "Not filled" : order.filled_on.to_formatted_s(:long)
  end
end

astro_dash/app/helpers/services_helper.rb
module ServicesHelper
end

astro_dash/app/helpers/sessions_helper.rb
module SessionsHelper
end

astro_dash/app/helpers/welcome_helper.rb
module WelcomeHelper
end

astro_dash/app/views/admin/orders/_form.html.erb
<%= form_for [:admin, @order] do |o| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited
        this order from being saved:</h2>
      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
      <%= o.label :customer %><br />
      <%= o.text_field :customer %>
  </p>
  <p>
    <%= o.label :email %><br />
    <%= o.email_field :email %>
  </p>
  <%= o.hidden_field :customer_info %>
  
    <!-- if no content, set to default 'Enter text here', otherwise render content for editing -->
  <% if @order.customer_info.nil? %>
    <%= render partial: 'shared/full_editor', locals: {content: "No customer info"} %>
  <% else %>
    <%= render partial: 'shared/full_editor', locals: {content: @order.customer_info} %>
  <% end %>
  
  <%= o.hidden_field :service_id %>
  
  <p>
    <%= o.submit %>
  </p>
  <p><%= debug(@order) %></p>
<% end %>

astro_dash/app/views/admin/orders/edit.html.erb
<h1>Edit an Order</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_orders_path %>

astro_dash/app/views/admin/orders/index.html.erb
<h1>Admin</h1>
<h2>Orders</h2>
<table class="table table-striped">
  <tr>
    <th>Order #</th>
    <th>Name</th>
    <th>Service</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
 
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.customer %></td>
      <td><%= order.service %></td>
      <td><%= order.status %></td>
      <td><%= link_to 'View order', admin_order_path(order) %></td>
      <td><%= link_to 'Edit', edit_admin_order_path(order) %></td>
      <td><%= link_to 'Destroy', admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Edit Content', admin_content_pages_path %>
<%= link_to 'Edit Events', admin_events_path %>

astro_dash/app/views/admin/orders/new.html.erb
<h2>Place an Order</h2>
<h3><%= @order.service.name %></h3>
<h3><%= @order.service.price %></h3>
<%= render 'form' %>
<%= link_to 'Back', admin_orders_path %>

astro_dash/app/views/admin/orders/show.html.erb
<h1>Order #<%= @order.id %></h1>
<ul>
    <li><%= @order.customer %></li>
    <li><%= @order.customer_info %></li>
    <li><%= @order.status %></li>
    <li><%= check_order_filled(@order) %></li>
    <li><%= @order.service.name %></li>
    <%= form_tag(admin_orders_send_path, id: 'send_docs_form', remote: true) do %>
      <%= hidden_field_tag(:id, @order.id) %>
      <%= hidden_field_tag(:files, '[{"name":"filename.txt","link":"https://...","bytes":464,"icon":"https://...","thumbnailLink":"https://...?bounding_box=75&mode=fit"}, {"name":"filename2.txt","link":"https://...","bytes":1464,"icon":"https://...","thumbnailLink":"https://...?bounding_box=75&mode=fit"}]') %>
      <%= submit_tag('Send Files') %>
    <% end %>
</ul>

astro_dash/app/views/orders/new.html.erb
<h2>Place an Order</h2>
<h3><%= @order.service.name %></h3>
<h3><%= @order.service.price %></h3>
<%= form_for @order do |o| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited
        this order from being saved:</h2>
      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
      <%= o.label :customer %><br />
      <%= o.text_field :customer %>
  </p>
  <p>
    <%= o.label :email %><br />
    <%= o.email_field :email %>
  </p>
  <%= o.hidden_field :customer_info %>
  <%= render 'shared/lite_editor' %>
  <%= o.hidden_field :service_id %>
  <p>
    <%= o.submit %>
  </p>
  <p><%= debug(@order) %></p>
<% end %>

astro_dash/app/views/orders/show.html.erb
<p>Thank you for your order.</p>
<p><%= @order.id %></p>
<p><%= @order.customer %></p>
<p><%= @order.customer_info %></p>
<p><%= @order.service.name %></p>
<p><%= @order.service.price %></p>
<p><%= debug(@order) %></p>