astro_dash/config/routes.rb
AstroDash::Application.routes.draw do
  
  
  root 'welcome#index'
  
  get "welcome/index"
  
  get 'content/:name' => 'content_pages#show'
  
  namespace :admin do
    post 'orders/send' => 'orders#send_documents'
    
    resources :services, :content_pages, :events, :orders
    get "index" => 'orders#index'
    
  end
  
  resources :services, :content_pages, :events, :only => [:index, :show]
  
  resources :orders, :only => [:show, :new, :create]
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  

end

astro_dash/app/models/concerns/html_sanitize.rb
# HTML Sanitizer
module HTML_Sanitize 
  extend ActiveSupport::Concern
  
  require 'sanitize'
  
  # sanitize HTML input using white list array of allowable HTML tags in config variables
  def sanitize(input) 
    Sanitize.fragment(input, 
      :elements => APP_CONFIG['HTML_white_list']['elements'],
      :attributes => {
        :all => APP_CONFIG['HTML_white_list']['attributes']
      })
  end
  
end

astro_dash/app/models/content_page.rb
class ContentPage < ActiveRecord::Base
  
  include HTML_Sanitize
    
  before_save do
    self.body = sanitize(self.body)
  end
  
end

astro_dash/app/models/event.rb
class Event < ActiveRecord::Base
  
  include HTML_Sanitize
    
  before_save do
    self.description = sanitize(self.description)
  end
end

astro_dash/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :service
  
end

astro_dash/app/models/service.rb
class Service < ActiveRecord::Base
  
  include HTML_Sanitize
  
  before_save do
    self.description = sanitize(self.description)
    self.required_info = sanitize(self.required_info)
  end
  
  validates :name, presence: true, length: {minimum: 5}
  validates :price, presence: true, numericality: true
end

astro_dash/app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
    
  def index
    @events = Event.all
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(event_params)
    
    if @event.save
      redirect_to [:admin, @event]
    else
      render 'new'
    end
    
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
   
    if @event.update(event_params)
      redirect_to [:admin, @event]
    else
      render 'edit'
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    
    redirect_to admin_events_path
  end
  
  private
    def event_params
      params.require(:event).permit(:name, :description, :date)
    end
end

astro_dash/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  
  # authenticate all requests to controllers in admin namespace
  before_filter :authenticate
  
  protected
  
  def authenticate
    if session[:username] != APP_CONFIG['username']
      redirect_to root_path
    end
  end
    
end

astro_dash/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

astro_dash/app/controllers/content_pages_controller.rb
class ContentPagesController < ApplicationController
  
  def show
    @content_pages = ContentPage.where(:category => params[:name]).all
  end
  
  def index
    @content_pages = ContentPage.find(:all, category: params[:name])
  end
  
end

astro_dash/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @events = Event.all
  end

end

astro_dash/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
    if @service.nil?
      @service = Service.find(params[:service_id])
    end
    @order = Order.new(:service => @service)
  end
  
  def show
    @order = Order.find(params[:id])
  end
  
  def create
    @order = Order.new(order_params)
    if @order.save
      OrderMailer.confirmation_email(@order).deliver
      redirect_to @order
    else
      render new
    end
  end
  
  private
    def order_params
      params.require(:order).permit(:customer, :customer_info, :email, :service_id)
    end
  
end

astro_dash/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  
  def index
    @services = Service.all
  end
  
  def show
    @service = Service.find(params[:id])
  end
  
  
end

astro_dash/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    login_id = params[:session][:login]
    login_pass = params[:session][:password]
    
    # if valid login, set session username
    if login_id == APP_CONFIG['username'] and login_pass == APP_CONFIG['password']
      session[:username] = login_id
      redirect_to admin_index_path
    else
      flash[:danger] = 'invalid login'
      render 'new'
    end
  end

  def destroy
    # username is only session variable, so simply reset entire session
    reset_session
    redirect_to root_path
  end
end

astro_dash/app/controllers/welcome_controller.rb
require 'rss'
require 'open-uri'

class WelcomeController < ApplicationController
  
  def index
    blog_rss_url = APP_CONFIG['rss_url']
    get_rss(blog_rss_url)
  end
  
  private
    def get_rss(rss_url)
      open(rss_url) do |rss|
        @feed = RSS::Parser.parse(rss)
      end
    end
end

astro_dash/app/helpers/admin/event_helper.rb
module Admin::EventHelper
end

astro_dash/app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

astro_dash/app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

astro_dash/app/helpers/admin_helper.rb
module AdminHelper
end

astro_dash/app/helpers/application_helper.rb
module ApplicationHelper
end

astro_dash/app/helpers/content_page_helper.rb
module ContentPageHelper
end

astro_dash/app/helpers/event_helper.rb
module EventHelper
end

astro_dash/app/helpers/orders_helper.rb
module OrdersHelper
  
  # checks if order is filled, if so, formats date
  def check_order_filled(order)
    order.filled_on.nil? ? "Not filled" : order.filled_on.to_formatted_s(:long)
  end
end

astro_dash/app/helpers/services_helper.rb
module ServicesHelper
end

astro_dash/app/helpers/sessions_helper.rb
module SessionsHelper
end

astro_dash/app/helpers/welcome_helper.rb
module WelcomeHelper
end

astro_dash/app/views/admin/events/_form.html.erb
<%= form_for [:admin, @event] do |e| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
      <%= e.label :name %><br />
      <%= e.text_field :name %>
  </p>
  
  <%= e.hidden_field :description %>
  
  <!-- if no content, set to default 'Enter text here', otherwise render content for editing -->
  <% if @event.description.nil? %>
    <%= render partial: 'shared/full_editor', locals: {content: "Enter text here"} %>
  <% else %>
    <%= render partial: 'shared/full_editor', locals: {content: @event.description} %>
  <% end %>

  <p>
    <%= e.label :date %><br />
    <%= e.date_field :date, :data => {:provide => 'datepicker', :'date-format' => 'dd-mm-yyyy'} %>
  </p>
  <p>
    <%= e.submit %>
  </p>
<% end %>

astro_dash/app/views/admin/events/edit.html.erb
<h1>Edit an Event</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_events_path %>

astro_dash/app/views/admin/events/index.html.erb
<h1>Listing events</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Date</th>
    <th colspan="3"></th>
  </tr>
 
  <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.description %></td>
      <td><%= event.date %></td>
      <td><%= link_to 'Show', admin_event_path(event) %></td>
      <td><%= link_to 'Edit', edit_admin_event_path(event) %></td>
      <td><%= link_to 'Destroy', admin_event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New event', new_admin_event_path %>

astro_dash/app/views/admin/events/new.html.erb
<h1>Add an Event</h1>

<%= render 'form' %>
<%= link_to 'Back', admin_events_path %>

astro_dash/app/views/admin/events/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @event.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @event.description %>
</p>

<p>
    <strong>date:</strong>
    <%= @event.date %>
</p>
<%= link_to 'Back', admin_events_path %>
| <%= link_to 'Edit', edit_admin_event_path(@event) %>

astro_dash/app/views/events/index.html.erb
<h1>Events</h1>
<% @events.each do |event| %>
<h1><%= event.name %></h1>
<h3><%= event.date %></h3>
<p><%= event.description %></p>
<% end %>